### ISSUE TITLE
readme.md and big thanks!

### ISSUE THREAD

**Issue by ksaadDE** [kunitoki/cxx-docker-images#9]
Hello,

I needed your gcc-6 Dockerfile for a specific task and just wanted to thank you very much for providing it! 

Further I would like to add `https://hub.docker.com/search?q=kunitoki` to your readme.md, so we can find your repositories since the `?namespace=<username>` does not work anymore.

Regards

**Comment by kunitoki** [comment]
You welcome ! Glad they are useful !

Update the readme, thanks.
